language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed 
  - docker build -t udagram-api-user 
  - docker build -t udagram-frontend 
  - docker build -t udagram-reverseproxy 
  - docker tag udagram-api-feed oluwaseun767/udagram-api-feed:latest
  - docker tag udagram-api-user oluwaseun767/udagram-api-user:latest
  - docker tag udagram-frontend oluwaseun767/udagram-frontend:latest
  - docker tag udagram-reverseproxy oluwaseun767/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push oluwaseun767/udagram-api-feed:latest
  - docker push oluwaseun767/udagram-api-user:latest
  - docker push oluwaseun767/udagram-frontend:latest
  - docker push oluwaseun767/udagram-reverseproxy:latest
